# Generated by Django 5.2.14 on 2026-09-18 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_vendor_notify_default_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Shown to customers on the booking form. Leave blank to use the default policy.'),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % applied to Our Price for the final customer-facing price.', max_digits=5),
        ),
        migrations.AddField(
            model_name='service',
            name='our_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Our Price — the customer-facing price. Falls back to the Hall Owner Price if left blank.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hall Owner Price — what the vendor charges. Not shown to customers.', max_digits=12),
        ),
        migrations.CreateModel(
            name='VendorStaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff_profile', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_users', to='services.vendor')),
            ],
        ),
    ]
