# Generated by Django 5.2.14 on 2026-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_parking_available_regional_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Shown on the home page hero, one image at a time. Up to 6 images are kept — uploading a new one beyond that automatically removes the oldest. Wide landscape photos (1600×900px or larger) work best.', upload_to='home_background/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers play first in the slideshow. Images with the same order play oldest-first.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Background Image',
                'verbose_name_plural': 'Home Background Images (max 6)',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]