# Generated by Django 5.2.14 on 2026-09-26 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_update_venue_filter_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/avatars/', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character IFSC code (e.g. SBIN0001234).', regex='^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code')),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='services.vendor')),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='HallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, help_text='15-character GST Identification Number (GSTIN).', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GST number (e.g. 22AAAAA0000A1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GST')),
                ('trade_license_number', models.CharField(blank=True, max_length=100, verbose_name='Trade License')),
                ('pan_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g. ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')], verbose_name='PAN Number')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall_details', to='services.vendor')),
            ],
            options={
                'verbose_name': 'Hall Details',
                'verbose_name_plural': 'Hall Details',
            },
        ),
    ]
    