# Generated by Django 5.2.14 on 2026-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(default='app_open', max_length=30)),
                ('route', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'created_at'], name='analytics_u_platfor_88c7c8_idx'), models.Index(fields=['device_id', 'created_at'], name='analytics_u_device__039686_idx')],
            },
        ),
    ]
